spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebooking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        type: trace

booking:
  bookingTableStructureFilePath: C:/_tmp/ebooking/ebooking-bk/untitled/config/bookingTableStructure.json

